name: lmart
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.5
  equatable: ^2.0.7
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  flutter:
    sdk: flutter
  flutter_local_notifications: ^18.0.1
  flutter_localization: ^0.3.1
  flutter_stripe: ^11.4.0
  flutter_svg: ^2.0.17
  fluttertoast: ^8.2.12
  get_it: ^8.0.3
  google_sign_in: ^6.2.2
  http: ^1.3.0
  image_cropper: ^9.0.0
  image_picker: ^1.1.2
  in_app_review: ^2.0.10
  intl: ^0.19.0
  json_annotation: ^4.9.0
  lucide_icons: ^0.257.0
  permission_handler: ^11.4.0
  provider: ^6.1.2
  shared_preferences: ^2.5.2

dev_dependencies:
  build_runner: ^2.4.15
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/

  fonts:
    - family: Proxima Nova
      fonts:
        - asset: assets/fonts/ProximaNova-Regular.otf
        - asset: assets/fonts/Proxima Nova-Thin.otf
